### ISSUE TITLE
add more comments in code

### ISSUE THREAD

**Issue by Zhaoyilunnn** [Zhaoyilunnn/qdao#10]

**Comment by raunakkumarsingh** [comment]
Please assign this task to me; I will ensure proper documentation.

**Comment by Zhaoyilunnn** [comment]
Hi @raunakkumarsingh, thanks for reaching out. I am willing to assign this task to you, could you please
1. Try to limit the number of commits and close this issue with a single pull request
2. If you'd like to add a detailed docstring to a function or class, please follow this [standard](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#docstring-sections) as we're planing to build documentation website for this project and this can help generate documents easily.

Thanks,

**Comment by raunakkumarsingh** [comment]
"I am following this format:  
![image](https://github.com/user-attachments/assets/bc1fbd06-62c1-4df4-b4ee-0ef31b077676)

Can I change an already written comment?"

**Comment by Zhaoyilunnn** [comment]
> I am following this format: ![image](https://private-user-images.githubusercontent.com/35128126/351831290-bc1fbd06-62c1-4df4-b4ee-0ef31b077676.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4NjY2NjcsIm5iZiI6MTcyMTg2NjM2NywicGF0aCI6Ii8zNTEyODEyNi8zNTE4MzEyOTAtYmMxZmJkMDYtNjJjMS00ZGY0LWI0ZWUtMGVmMzFiMDc3Njc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDAwMTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZGRlNjIxZTVjMGM4YjA2MzY0MzQ0NGQ1MDg2NDYzMjk4YjkzYjExOTMxNGIyZGRkOTA3YmIxYmJmMjljOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fqpeg21YiQbLXgTwcyVn7CdsOYzt6_hMYZUAXVHk7aw)
> 
> Can I change an already written comment?

Yes of course
