### ISSUE TITLE
There is a package dependency issue

### ISSUE THREAD

**Issue by fxfxfxfxfxfxfxfx** [Zhaoyilunnn/qdao#15]
![image](https://github.com/Zhaoyilunnn/qdao/assets/49065560/652847d8-15c2-4301-a225-6ac8b6c1753d)

**Comment by Zhaoyilunnn** [comment]
qdao has been updated to 0.1.2, try to sync with upstream and then reinstall qdao

**Comment by fxfxfxfxfxfxfxfx** [comment]
haode
